In [ ]:
import numpy as np
import tensorflow as tf

#Style Target

![Image](https://cxl-web-prod-uploads.s3.amazonaws.com/public/pagedown-uploads/ea8b739627d743145c9e1fda0310532d59dbb787.png)

#Gram matrix

##A small numpy array

In [ ]:
np.random.seed(0)
x = np.random.randint(0,3, (2, 2, 2))

In [ ]:
print(x.shape)
print(x[:,:,0])
print(x[:,:,1])

(2, 2, 2)
[[0 0]
 [1 0]]
[[1 1]
 [2 2]]


In [ ]:
a = tf.linalg.einsum('ijc,ijd->cd', x ,x)
print(a.shape)
print(a)

(2, 2)
tf.Tensor(
[[ 1  2]
 [ 2 10]], shape=(2, 2), dtype=int64)


##Another example

In [ ]:
np.random.seed(1)
x = np.random.randint(0,3, (1, 2, 2, 2))
# Why number 1?

In [ ]:
print(x.shape)
print(x[:,:,:,0])
print(x[:,:,:,1])

(1, 2, 2, 2)
[[[1 0]
  [1 0]]]
[[[0 1]
  [0 1]]]


In [ ]:
a = tf.linalg.einsum('bijc,bijd->bcd', x ,x)
print(a.shape)
print(a)

(1, 2, 2)
tf.Tensor(
[[[2 0]
  [0 2]]], shape=(1, 2, 2), dtype=int64)


##A function for the general case

In [ ]:
def gram_matrix(input_tensor):

  result = tf.linalg.einsum('bijc,bijd->bcd', input_tensor, input_tensor)

  input_shape = tf.shape(input_tensor)

  num_locations = tf.cast(input_shape[1]*input_shape[2], tf.float32)
  
  return result/(num_locations)

#tf.reduce_mean()

`tf.reduce_mean()`:Computes the mean of elements across dimensions of a tensor.

`tf.add_n()`: Adds all input tensors element-wise.

In [ ]:
np.random.seed(1)
A = np.random.randint(0, 4, (1, 2, 2, 4))
B = np.random.randint(0, 4, (1, 2, 2, 4))

A = A.astype(float)
B = B.astype(float)

print(A[0,:,:,0])
print(B[0,:,:,0])

[[1. 3.]
 [3. 0.]]
[[2. 2.]
 [3. 1.]]


In [ ]:
#print all the feature maps
for i in range(4):
  print(i)
  print(A[0,:,:,i])
  print(B[0,:,:,i])

0
[[1. 3.]
 [3. 0.]]
[[2. 2.]
 [3. 1.]]
1
[[3. 1.]
 [0. 3.]]
[[1. 1.]
 [0. 2.]]
2
[[0. 3.]
 [0. 1.]]
[[2. 2.]
 [2. 2.]]
3
[[0. 1.]
 [1. 0.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
(A-B)**2

array([[[[1., 4., 4., 0.],
         [1., 0., 1., 1.]],

        [[0., 0., 4., 1.],
         [1., 1., 1., 0.]]]])

In [ ]:
a = tf.reduce_mean((A-B)**2)
print(a.numpy())

1.25


In [ ]:
b = tf.add_n([tf.reduce_mean((A-B)**2)])
print(b.numpy())

1.25
