In [ ]:
import numpy as np
from numpy import asarray
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2DTranspose, UpSampling2D

In [ ]:
np.set_printoptions(precision = 2)

#UpSampling2D layer

In [ ]:
i = 2 # input size

In [ ]:
# input data
np.random.seed(1)

X = np.random.randn(i, i)
print(X)

[[ 1.62 -0.61]
 [-0.53 -1.07]]


In [ ]:
# Reshape input data into one sample a sample with a channel
X = X.reshape((1, i, i, 1))

print("X.shape = ", X.shape)

X.shape =  (1, 2, 2, 1)


In [ ]:
# Define a model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), size = (3, 3), interpolation='nearest'))

# Model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 up_sampling2d_1 (UpSampling  (None, 6, 6, 1)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [ ]:
X_hat = model.predict(X)
print("X_hat.shape = ", X_hat.shape)

X_hat.shape =  (1, 6, 6, 1)


In [ ]:
# Reshape X_hat 
X_hat = np.squeeze(X_hat, axis = 0)
X_hat = np.squeeze(X_hat, axis = 2)

print("X_hat.shape = ", X_hat.shape)

X_hat.shape =  (6, 6)


In [ ]:
print(X_hat)

[[ 1.62  1.62  1.62 -0.61 -0.61 -0.61]
 [ 1.62  1.62  1.62 -0.61 -0.61 -0.61]
 [ 1.62  1.62  1.62 -0.61 -0.61 -0.61]
 [-0.53 -0.53 -0.53 -1.07 -1.07 -1.07]
 [-0.53 -0.53 -0.53 -1.07 -1.07 -1.07]
 [-0.53 -0.53 -0.53 -1.07 -1.07 -1.07]]


#Conv2DTranspose layer

In [ ]:
i = 7 # input size
s = 3 # stride
k = 4 # kernel size

In [ ]:
# input data
X = np.random.rand(i, i)
print(X)

[[0.4  0.54 0.42 0.69 0.2  0.88 0.03]
 [0.67 0.42 0.56 0.14 0.2  0.8  0.97]
 [0.31 0.69 0.88 0.89 0.09 0.04 0.17]
 [0.88 0.1  0.42 0.96 0.53 0.69 0.32]
 [0.69 0.83 0.02 0.75 0.99 0.75 0.28]
 [0.79 0.1  0.45 0.91 0.29 0.29 0.13]
 [0.02 0.68 0.21 0.27 0.49 0.05 0.57]]


In [ ]:
# Reshape input data into one sample a sample with a channel
X = X.reshape((1, i, i, 1))

print("X.shape = ", X.shape)

X.shape =  (1, 7, 7, 1)


In [ ]:
# Define a model
model = Sequential()
model.add(Conv2DTranspose(filters = 1, 
                          kernel_size = (k, k), 
                          strides = (s, s), 
                          input_shape=(i, i, 1),
                          padding = 'same'
                          ))

# Model summary
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose_1 (Conv2DT  (None, 21, 21, 1)        17        
 ranspose)                                                       
                                                                 
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [ ]:
X_hat = model.predict(X)

print("X_hat.shape = ", X_hat.shape)

X_hat.shape =  (1, 21, 21, 1)


In [ ]:
# Reshape X_hat 
X_hat = np.squeeze(X_hat, axis = 0)
X_hat = np.squeeze(X_hat, axis = 2)

print("X_hat.shape = ", X_hat.shape)

X_hat.shape =  (21, 21)


In [ ]:
print(X_hat)

[[ 3.76e-02  1.50e-01 -1.23e-01 -1.15e-02  2.03e-01 -1.67e-01 -4.52e-02
   1.58e-01 -1.30e-01 -1.15e-03  2.59e-01 -2.13e-01 -8.87e-02  7.72e-02
  -6.35e-02  5.10e-02  3.31e-01 -2.73e-01 -1.36e-01  1.03e-02 -8.51e-03]
 [ 9.17e-02 -5.58e-02  4.82e-02  5.47e-02 -7.58e-02  6.55e-02  2.09e-03
  -5.90e-02  5.10e-02  8.46e-02 -9.64e-02  8.33e-02 -7.33e-02 -2.88e-02
   2.49e-02  1.67e-01 -1.24e-01  1.07e-01 -1.48e-01 -3.85e-03  3.33e-03]
 [ 1.59e-01 -5.71e-02 -1.16e-01  2.13e-01 -7.75e-02 -1.57e-01  1.64e-01
  -6.03e-02 -1.22e-01  2.72e-01 -9.86e-02 -2.00e-01  7.74e-02 -2.94e-02
  -5.97e-02  3.50e-01 -1.26e-01 -2.56e-01  5.21e-03 -3.94e-03 -7.99e-03]
 [-2.33e-02  8.40e-02 -3.50e-01 -4.32e-02 -7.21e-02 -3.22e-01  8.67e-02
   3.22e-02 -3.23e-01 -7.59e-02 -2.39e-01 -2.88e-01  1.95e-01 -1.24e-02
  -1.35e-01 -7.49e-02 -7.20e-02 -5.62e-01  2.71e-01  3.54e-01 -3.11e-01]
 [ 1.55e-01 -9.43e-02  8.15e-02 -2.15e-02 -5.87e-02  5.07e-02  5.57e-02
  -7.86e-02  6.79e-02 -6.58e-02 -1.97e-02  1.71e-02  2.11e-0